/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fighterfinderadmin.view;

import fighterfinderadmin.controller.Controller;
import fighterfinderadmin.entities.ACharacter;
import fighterfinderadmin.entities.AGame;
import fighterfinderadmin.entities.Model;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Adrian
 */
public class AddCharacterPanel extends javax.swing.JPanel {
    
    private Controller myController;
    private Model myModel;
    private int currentGameID = -1;
    private List<AGame> aGList;
    private List<ACharacter> aCList;
    /**
     * Creates new form AddCharacterPanel
     */
    public AddCharacterPanel() {
        initComponents();
    }
    
    public AddCharacterPanel(Controller aController, Model aModel) {
        initComponents();
        this.myController = aController;
        this.myModel = aModel;
        fillGamesCombobox();
        addCustomCB();
    }
    /**
     * fillGamesCombobox
     * Method to fill the combobox with the database data
     * 
     */
    private void fillGamesCombobox()
    {
        AGame[] arrTest = new AGame[]{new AGame(1, "Game 1"),new AGame(2, "Game 2"),new AGame(3, "Game 3")};
        this.myModel.setMyGameList(this.myController.getAllGamesFromDatabase());
        this.aGList = this.myModel.getMyGameList();
        //this.currentGameID = this.aGList.get(0).getId();
        //AGame[] gArray = new AGame[this.aGList.size()];
        //this.aGList.toArray(gArray);
        gameListCB.setModel(new DefaultComboBoxModel(this.aGList.toArray()));
        System.out.println(this.currentGameID);
        jComboBox1.setModel(new DefaultComboBoxModel(arrTest));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newCharNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gameListCB = new javax.swing.JComboBox();
        addCharBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("Character name: ");

        jLabel2.setText("Game: ");

        gameListCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "item 1", "item 2", "item 3", "item 4" }));
        gameListCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameListCBActionPerformed(evt);
            }
        });

        addCharBtn.setText("Add character");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(newCharNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(gameListCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(addCharBtn)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newCharNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gameListCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCharBtn)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        System.out.println(jComboBox1.getSelectedItem().toString());
        //jComboBox1.getS
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void gameListCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameListCBActionPerformed
        // TODO add your handling code here:
        AGame aG = (AGame)gameListCB.getSelectedItem();
        this.currentGameID = aG.getId();
        System.out.println(this.currentGameID);
    }//GEN-LAST:event_gameListCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCharBtn;
    private javax.swing.JComboBox gameListCB;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField newCharNameTF;
    // End of variables declaration//GEN-END:variables

    private void addCustomCB() {
        JComboBox comboBox = new JComboBox(this.aGList.toArray());
        comboBox.addItemListener(new ItemListener() {
            //
            // Listening if a new items of the combo box has been selected.
            //
            @Override
            public void itemStateChanged(ItemEvent event) {
                JComboBox comboBox = (JComboBox) event.getSource();

                // The item affected by the event.
                Object item = event.getItem();
                System.out.println(item);
            }
        });
        add(comboBox);
    }
}
