/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fighterfinderadmin.view;

import fighterfinderadmin.controller.Controller;
import fighterfinderadmin.entities.AGame;
import fighterfinderadmin.entities.Model;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Adrian
 */
public class AddCharacterPanel extends javax.swing.JPanel {
    
    private Controller myController;
    private Model myModel;
    private int currentGameID = -1;
    /**
     * Creates new form AddCharacterPanel
     */
    public AddCharacterPanel() {
        initComponents();
    }
    
    public AddCharacterPanel(Controller aController, Model aModel) {
        initComponents();
        this.myController = aController;
        this.myModel = aModel;
        fillGamesCombobox();
    }
    /**
     * fillGamesCombobox
     * Method to fill the combobox with the database data
     * 
     */
    private void fillGamesCombobox()
    {
        this.myModel.setMyGameList(this.myController.getAllGamesFromDatabase());
        this.currentGameID = this.myModel.getMyGameList().get(0).getId();
        gameListCB.setModel(new DefaultComboBoxModel(this.myModel.getMyGameList().toArray()));
        System.out.println(this.currentGameID);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newCharNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gameListCB = new javax.swing.JComboBox();
        addCharBtn = new javax.swing.JButton();

        jLabel1.setText("Character name: ");

        jLabel2.setText("Game: ");

        gameListCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "item 1", "item 2", "item 3", "item 4" }));
        gameListCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCurrentGameID(evt);
            }
        });

        addCharBtn.setText("Add character");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCharBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newCharNameTF)
                            .addComponent(gameListCB, 0, 200, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newCharNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gameListCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(addCharBtn)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setCurrentGameID(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCurrentGameID
        // TODO add your handling code here:
        AGame aG = (AGame)gameListCB.getSelectedItem();
        this.currentGameID = aG.getId();
        System.out.println(aG.getId());
    }//GEN-LAST:event_setCurrentGameID


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCharBtn;
    private javax.swing.JComboBox gameListCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField newCharNameTF;
    // End of variables declaration//GEN-END:variables
}
