/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fighterfinderadmin.view;

import fighterfinderadmin.controller.Controller;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumne
 */
public class MainView extends javax.swing.JFrame {
    static final String ABOUT = "App made by Adrián de Feo Martínez and Albert Muñoz\nAdmin panel for FighterFinder\nVersion 0.8\nEmail: adriandefeomartinez@gmail.com\nCopyright 2016";
    private Controller myController;
    /**
     * Creates new form MainFrame
     */
    public MainView() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        hideAll();
    }
    
    public MainView(Controller aController)
    {
        initComponents();
        this.myController = aController;
        this.myController.setMyView(this);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        hideAll();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        charPanel = new javax.swing.JPanel();
        addNewCharPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        modCharPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        addGamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        modGamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        userMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        gameMenu = new javax.swing.JMenu();
        addGameItMenu = new javax.swing.JMenuItem();
        modGameItMenu = new javax.swing.JMenuItem();
        charMenu = new javax.swing.JMenu();
        addNewCharItMenu = new javax.swing.JMenuItem();
        modCharacterItMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                closeApp(evt);
            }
        });

        jLabel1.setText("User panel");

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Add character panel");

        javax.swing.GroupLayout addNewCharPanelLayout = new javax.swing.GroupLayout(addNewCharPanel);
        addNewCharPanel.setLayout(addNewCharPanelLayout);
        addNewCharPanelLayout.setHorizontalGroup(
            addNewCharPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewCharPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(66, 66, 66))
        );
        addNewCharPanelLayout.setVerticalGroup(
            addNewCharPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewCharPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel5.setText("Mod character panel");

        javax.swing.GroupLayout modCharPanelLayout = new javax.swing.GroupLayout(modCharPanel);
        modCharPanel.setLayout(modCharPanelLayout);
        modCharPanelLayout.setHorizontalGroup(
            modCharPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modCharPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(74, 74, 74))
        );
        modCharPanelLayout.setVerticalGroup(
            modCharPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modCharPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout charPanelLayout = new javax.swing.GroupLayout(charPanel);
        charPanel.setLayout(charPanelLayout);
        charPanelLayout.setHorizontalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addNewCharPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, charPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modCharPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        charPanelLayout.setVerticalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charPanelLayout.createSequentialGroup()
                .addComponent(addNewCharPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modCharPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Add game panel");

        javax.swing.GroupLayout addGamePanelLayout = new javax.swing.GroupLayout(addGamePanel);
        addGamePanel.setLayout(addGamePanelLayout);
        addGamePanelLayout.setHorizontalGroup(
            addGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addGamePanelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(100, 100, 100))
        );
        addGamePanelLayout.setVerticalGroup(
            addGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addGamePanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel3.setText("Mod game panel");

        javax.swing.GroupLayout modGamePanelLayout = new javax.swing.GroupLayout(modGamePanel);
        modGamePanel.setLayout(modGamePanelLayout);
        modGamePanelLayout.setHorizontalGroup(
            modGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modGamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(103, 103, 103))
        );
        modGamePanelLayout.setVerticalGroup(
            modGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modGamePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addComponent(addGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(modGamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addComponent(addGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainContainerLayout.createSequentialGroup()
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(charPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(charPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        userMenu.setText("Users");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserPanel(evt);
            }
        });
        userMenu.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        userMenu.add(jMenuItem2);

        jMenuBar1.add(userMenu);

        gameMenu.setText("Games");

        addGameItMenu.setText("Add new game");
        addGameItMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAddNewGamePanel(evt);
            }
        });
        gameMenu.add(addGameItMenu);

        modGameItMenu.setText("Modify game");
        modGameItMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showModGamePanel(evt);
            }
        });
        gameMenu.add(modGameItMenu);

        jMenuBar1.add(gameMenu);

        charMenu.setText("Characters");

        addNewCharItMenu.setText("Add new character");
        addNewCharItMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCharItMenuActionPerformed(evt);
            }
        });
        charMenu.add(addNewCharItMenu);

        modCharacterItMenu.setText("Modify character");
        modCharacterItMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showModCharPanel(evt);
            }
        });
        charMenu.add(modCharacterItMenu);

        jMenuBar1.add(charMenu);

        aboutMenu.setText("About");
        aboutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAbout(evt);
            }
        });
        jMenuBar1.add(aboutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     /**
     * closeApp
     * Method to close the app
     */
    private void closeApp(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeApp
        // TODO add your handling code here:
        this.myController.closeApp();
    }//GEN-LAST:event_closeApp
    
    
    //METHODS TO SHOW AND HIDE THE PANELS IN ADMIN STUFF
    private void showAbout(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAbout
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, ABOUT, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_showAbout

    private void addNewCharItMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCharItMenuActionPerformed
        // TODO add your handling code here:
        /*hideAll();
        charPanel.setVisible(true);
        addNewCharPanel.setVisible(true);
        System.out.println("test");*/
    }//GEN-LAST:event_addNewCharItMenuActionPerformed

    private void showModCharPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showModCharPanel
        // TODO add your handling code here:
        /*hideAll();
        charPanel.setVisible(true);
        modCharPanel.setVisible(true);*/
    }//GEN-LAST:event_showModCharPanel

    private void showAddNewGamePanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAddNewGamePanel
        // TODO add your handling code here:
        /*hideAll();
        gamePanel.setVisible(true);
        addGamePanel.setVisible(true);*/
    }//GEN-LAST:event_showAddNewGamePanel

    private void showModGamePanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showModGamePanel
        // TODO add your handling code here:
        /*hideAll();
        gamePanel.setVisible(true);
        modGamePanel.setVisible(true);*/
    }//GEN-LAST:event_showModGamePanel

    private void showUserPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserPanel
        // TODO add your handling code here:
        /*hideAll();
        userPanel.setVisible(true);*/
    }//GEN-LAST:event_showUserPanel
    
    private void hideAll()
    {
        //hide all the panels
        /*userPanel.setVisible(false);
        gamePanel.setVisible(false);
        charPanel.setVisible(false);
        modGamePanel.setVisible(false);
        addGamePanel.setVisible(false);
        modCharPanel.setVisible(false);
        addNewCharPanel.setVisible(false);*/
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem addGameItMenu;
    private javax.swing.JPanel addGamePanel;
    private javax.swing.JMenuItem addNewCharItMenu;
    private javax.swing.JPanel addNewCharPanel;
    private javax.swing.JMenu charMenu;
    private javax.swing.JPanel charPanel;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel modCharPanel;
    private javax.swing.JMenuItem modCharacterItMenu;
    private javax.swing.JMenuItem modGameItMenu;
    private javax.swing.JPanel modGamePanel;
    private javax.swing.JMenu userMenu;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
